<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" Version="6.0.0" />
  </ItemGroup>

  <!-- Compile-time reference to any DLLs placed under Plugins/ -->
  <ItemGroup>
    <PluginDll Include="Plugins\*.dll" />
    <PluginXml Include="Plugins\*.xml" />
    <PluginPdb Include="Plugins\*.pdb" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AIRBattleSimulation">
      <HintPath>.\Plugins\AIRBattleSimulation.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <!-- Ensure these files live in the same folder as the DLL -->
    <None Include="Plugins\AIRBattleSimulation.xml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Plugins\AIRBattleSimulation.pdb" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
